version: '2'
services:
  mail:
    container_name: talea_mail
    image: namshi/smtp
  app:
    build: .
    command: ./script/start
    working_dir: /var/www/talea
    depends_on:
      - db
    volumes:
      - ./talea:/var/www/talea:Z
      - ./mount/log:/var/www/talea/log:Z
      - ./mount/public:/var/www/talea/public:Z
      - ./mount/tmp:/var/www/talea/tmp:Z
      - ./mount/bundle:/usr/local/bundle:Z
      - ./override/database.yml:/var/www/talea/config/database.yml:Z
      - ./script/start:/var/www/talea/script/start:Z
    expose:
      - "3000"
    container_name: talea
    links:
      - db
    env_file:
      - rails_variables.env

  web:
    build:
      context: ./
      dockerfile: Dockerfile-nginx
    links:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:Z
      - ./nginx/log:/var/log/nginx:Z
    container_name: talea_nginx
    ports:
      - '80:80'
  db:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./database_initial:/docker-entrypoint-initdb.d:Z
      - /home/pandre/Working/Docker/mariadb-talea:/var/lib/mysql:Z
      - ./mysql/rebuild.sh:/var/dbs/rebuild.sh:Z
      - ./dumps/:/var/dbs/data:Z
    ports:
      - 3306:3306
    container_name: talea_mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: talea_phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=password
      - PMA_HOST=db
    restart: always
    ports:
      - 8090:80
    volumes:
      - /sessions
    links:
      - db
